print("What is your name?", end= ' ')
name = input()
print("How old are you?", end=' ')
age = input()
print("How tall are you?", end =' ')
height = input()
print("How much do you weigh?", end= ' ')
weight = input()

print(f"So, your name is {name}, you're {age} old, {height} tall and {weight} heavy.")
